dist: bionic

language: minimal

install:
  - curl -fsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  - fin test
  - fin d8-core-update
    ## Run only 'fin test' on update
    #~if: branch = update

after_success:
  - fin deploy 
