dist: bionic

language: minimal

install:
  - curl -fsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  - fin test
  ## NOTE: temporarily add '--local' while debugging. 
  ## Travis cron only run once daily so it's quite hard to debug.
  - fin drupal-coreupdate --local

after_success:
  - fin deploy

notifications:
  email:
    recipients:
      - sysadmin@prometsource.com
      #- aaron@prometsource.com
    on_success: always # default: change
    on_failure: always # default: always
  slack:
    rooms:
    - prometsourcegroup:${SLACK_TOKEN}#provus
