dist: bionic

language: minimal

install:
  ## Update 'get.docksal.io' curl fails from time to time. Added '-k' to ignore cert error.
  ## ==> curl: (51) SSL: no alternative certificate subject name matches target host name 'get.docksal.io'
  - curl -kfsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  ## NOTE: Travis cron only run once daily. To debug, temporarily add '--local' to 'fin drupal-coreupdate'.
  ##       * Run 'try', 'test' and 'sendpr' this way so it stops once preceeding command fails for quick feedback.
  - fin drupal-coreupdate try && fin test && fin drupal-coreupdate sendpr

after_success:
  - fin deploy

notifications:
    on_success: always # default: change
    on_failure: always # default: always
