dist: bionic

language: minimal
notifications:
  slack:
    rooms:
    - prometsourcegroup:${SLACK_TOKEN}#general

install:
  - curl -fsSL https://get.docksal.io | bash
  - fin update
  - fin version
  - fin sysinfo

before_script:
  - fin init

script:
  - fin test
  - fin drupal-coreupdate

after_success:
  - fin deploy
